[package]
name = "datamaxi"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT"

[dependencies]
dotenv = "0.15.0"
api = "0.2.0"
error-chain = "0.12.4"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
tungstenite = "0.24.0"
url = "2.5.2"

[dev-dependencies]
mockito = "1.5.0"
